export const ActionTypes = {
    FETCH_PRODUCTS_REQUEST : 'FETCH_PRODUCTS_REQUEST',
    FETCH_PRODUCTS_SUCCESS : 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILURE : 'FETCH_PRODUCTS_FAILURE',
    SELECTED_PRODUCT: 'SELECTED_PRODUCT',
    REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
}